{
  "timestamp": "{{now}}",
  "hostname": "{{randoms "web-server-01|web-server-02|app-server-01|app-server-02|db-server-01|db-server-02|mail-server-01|dns-server-01|proxy-server-01|jump-host-01|k8s-master-01|k8s-worker-01|k8s-worker-02|jenkins-01|gitlab-01|monitoring-01"}}",
  "ip_address": "{{randoms "10.10.1.10|10.10.1.20|10.10.2.10|10.10.2.20|10.10.3.10|10.10.3.20|172.16.0.10|172.16.1.10|192.168.1.10|192.168.2.10"}}",
  "facility": "{{randoms "kern|user|mail|daemon|auth|syslog|lpr|news|uucp|cron|authpriv|ftp|local0|local1|local2|local3|local4|local5|local6|local7"}}",
  "severity": "{{randoms "emerg|alert|crit|err|warning|notice|info|info|info|info|debug"}}",
  "severity_code": {{integer 0 7}},
  "priority": {{integer 0 191}},
  "process_name": "{{randoms "sshd|systemd|kernel|cron|postfix|nginx|apache2|mysqld|postgres|docker|kubelet|containerd|rsyslogd|auditd|firewalld|NetworkManager|dhclient|ntpd"}}",
  "process_id": {{integer 1 65535}},
  "message_id": "{{random_string_vocabulary 8 12 "0123456789ABCDEF"}}",
  "structured_data": "{{randoms "-|-|[timeQuality tzKnown=1 isSynced=1]|[origin software=rsyslogd swVersion=8.2]|[meta sequenceId=123]"}}",
  "message": "{{randoms "User login successful|User logout|Authentication failure|Connection established|Connection closed|Service started|Service stopped|Configuration reloaded|Disk space low|Memory usage high|CPU usage high|Network interface down|Network interface up|Backup completed|Backup failed|Certificate expiring soon|SSL handshake failed|Database connection lost|Database connection restored|Cache cleared|Session expired|File not found|Permission denied|Invalid request|Rate limit exceeded|Health check passed|Health check failed|Deployment started|Deployment completed|Deployment failed|Container started|Container stopped|Pod created|Pod deleted|Node ready|Node not ready"}}",
  "source_ip": "{{randoms "10.10.1.45|10.10.2.67|192.168.1.100|172.16.0.50|203.0.113.45|198.51.100.23"}}",
  "user": "{{randoms "root|admin|sysadmin|operator|service|nobody|www-data|nginx|mysql|postgres|redis|elasticsearch|kafka|jenkins|gitlab|prometheus"}}",
  "event_type": "{{randoms "authentication|authorization|system|application|security|network|database|service|deployment|monitoring"}}",
  "protocol": "{{randoms "syslog|rsyslog|syslog-ng|RFC5424|RFC3164|CEF|LEEF"}}",
  "version": "{{randoms "1|2|3"}}",
  "tags": "{{randoms "production|staging|development|critical|warning|info|security|audit|compliance|performance"}}"
}