{
  "type": "record",
  "name": "DswtCustomersRecord",
  "namespace": "io.confluent.dswt",
  "fields": [
    {
      "name": "customer_id",
      "type": "string"
    },
    {
      "name": "first_name",
      "type": "string"
    },
    {
      "name": "last_name",
      "type": "string"
    },
    {
      "name": "email",
      "type": "string"
    },
    {
      "name": "segment",
      "type": "string"
    },
    {
      "name": "loyalty_tier",
      "type": "string"
    },
    {
      "name": "country",
      "type": "string"
    },
    {
      "name": "lifetime_orders",
      "type": "long"
    },
    {
      "name": "signup_ts",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    }
  ]
}
