{
  "type": "record",
  "name": "DswtPaymentsRecord",
  "namespace": "io.confluent.dswt",
  "fields": [
    {
      "name": "order_id",
      "type": "string"
    },
    {
      "name": "payment_method",
      "type": "string"
    },
    {
      "name": "amount",
      "type": "double"
    },
    {
      "name": "currency",
      "type": "string"
    },
    {
      "name": "status",
      "type": "string"
    },
    {
      "name": "authorized_ts",
      "type": {
        "type": "string",
        "logicalType": "iso-8601-timestamp"
      }
    }
  ]
}
